from django.urls import path
from .views import (
    CPUView, CoolerView, MotherboardView, RAMView, GPUView,
    StorageView, PowerSupplyView, TowerView, OperatingSystemView, MonitorView,
    ProductView, ProductTypeView, SystemIntegratorView, BuildAPC_ConfigView,
    CustomerView, ReviewView, CustomerWishListView, HumanResourceView, admin_home, user_home,
)

urlpatterns = [
    path('cpus/', CPUView.as_view(), name='cpu-list'),
    path('cpus/<int:pk>/', CPUView.as_view(), name='cpu-detail'),
    path('coolers/', CoolerView.as_view(), name='cooler-list'),
    path('coolers/<int:pk>/', CoolerView.as_view(), name='cooler-detail'),
    path('motherboards/', MotherboardView.as_view(), name='motherboard-list'),
    path('motherboards/<int:pk>/', MotherboardView.as_view(), name='motherboard-detail'),
    path('rams/', RAMView.as_view(), name='ram-list'),
    path('rams/<int:pk>/', RAMView.as_view(), name='ram-detail'), 
    path('gpus/', GPUView.as_view(), name='gpu-list'),
    path('gpus/<int:pk>/', GPUView.as_view(), name='gpu-detail'),
    path('storages/', StorageView.as_view(), name='storage-list'),
    path('storages/<int:pk>/', StorageView.as_view(), name='storage-detail'),
    path('powersupplies/', PowerSupplyView.as_view(), name='powersupply-list'),
    path('powersupplies/<int:pk>/', PowerSupplyView.as_view(), name='powersupply-detail'),
    path('towers/', TowerView.as_view(), name='tower-list'),
    path('towers/<int:pk>/', TowerView.as_view(), name='tower-detail'),
    path('operatingsystems/', OperatingSystemView.as_view(), name='operatingsystem-list'),
    path('operatingsystems/<int:pk>/', OperatingSystemView.as_view(), name='operatingsystem-detail'),
    path('monitors/', MonitorView.as_view(), name='monitor-list'),
    path('monitors/<int:pk>/', MonitorView.as_view(), name='monitor-detail'),
    path('products/', ProductView.as_view(), name='product-list'),
    path('products/<int:pk>/', ProductView.as_view(), name='product-detail'),
    path('producttypes/', ProductTypeView.as_view(), name='producttype-list'),
    path('producttypes/<int:pk>/', ProductTypeView.as_view(), name='producttype-detail'),
    path('systemintegrators/', SystemIntegratorView.as_view(), name='systemintegrator-list'),
    path('systemintegrators/<int:pk>/', SystemIntegratorView.as_view(), name='systemintegrator-detail'),
    path('configurations/', BuildAPC_ConfigView.as_view(), name='configuration-list'),
    path('configurations/<int:pk>/', BuildAPC_ConfigView.as_view(), name='configuration-detail'),
    path('customers/', CustomerView.as_view(), name='customer-list'),
    path('customers/<int:pk>/', CustomerView.as_view(), name='customer-detail'),
    path('reviews/', ReviewView.as_view(), name='review-list'),
    path('reviews/<int:pk>/', ReviewView.as_view(), name='review-detail'),
    path('wishlists/', CustomerWishListView.as_view(), name='wishlist-list'),
    path('wishlists/<int:pk>/', CustomerWishListView.as_view(), name='wishlist-detail'),
    path('humanresources/', HumanResourceView.as_view(), name='humanresource-list'),
    path('humanresources/<int:pk>/', HumanResourceView.as_view(), name='humanresource-detail'),
    path('admin/home/', admin_home, name='admin_home'),
    path('user/home/', user_home, name='user_home'),
]