# Generated by Django 4.2.10 on 2024-05-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city_state_zip', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('role_title', models.CharField(max_length=255)),
                ('cost_center', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('vendor_sku', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=800)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=800)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='SystemIntegrator',
            fields=[
                ('system_builder_id', models.AutoField(primary_key=True, serialize=False)),
                ('pcsys_build_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.producttype')),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('stg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=800)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_review', models.CharField(max_length=50)),
                ('system_integrator_review', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('ram_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=800)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=800)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('os_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=800)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('mb_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=800)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('mon_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=800)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('gpu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=800)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWishList',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('cpu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=800)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('cooler_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=800)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='BuildAPC_Config',
            fields=[
                ('cust_build_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.customer')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.producttype')),
                ('system_integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.systemintegrator')),
                ('vendor_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildapc_app.product')),
            ],
        ),
    ]
