# Generated by Django 4.2.10 on 2024-05-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildapc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildapc_config',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='cooler',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='operatingsystem',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='powersupply',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='systemintegrator',
            name='vendor_sku',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='vendor_sku',
        ),
        migrations.AddField(
            model_name='buildapc_config',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooler',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpu',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitor',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboard',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powersupply',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemintegrator',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tower',
            name='vendor_sku_id',
            field=models.CharField(default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_sku',
            field=models.CharField(max_length=23, primary_key=True, serialize=False),
        ),
    ]
